package com.entity;
// Generated Sep 7, 2019 8:57:10 PM by Hibernate Tools 4.3.1



/**
 * Report generated by hbm2java
 */
public class Report  implements java.io.Serializable {


     private Integer id;
     private String companyName;
     private String busNumber;
     private String salesTicket;
     private Double ticketPrice;
     private Double totalPrice;
     private Double totalCost;
     private Double totalPay;

    public Report() {
    }

    public Report(String companyName, String busNumber, String salesTicket, Double ticketPrice, Double totalPrice, Double totalCost, Double totalPay) {
       this.companyName = companyName;
       this.busNumber = busNumber;
       this.salesTicket = salesTicket;
       this.ticketPrice = ticketPrice;
       this.totalPrice = totalPrice;
       this.totalCost = totalCost;
       this.totalPay = totalPay;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getBusNumber() {
        return this.busNumber;
    }
    
    public void setBusNumber(String busNumber) {
        this.busNumber = busNumber;
    }
    public String getSalesTicket() {
        return this.salesTicket;
    }
    
    public void setSalesTicket(String salesTicket) {
        this.salesTicket = salesTicket;
    }
    public Double getTicketPrice() {
        return this.ticketPrice;
    }
    
    public void setTicketPrice(Double ticketPrice) {
        this.ticketPrice = ticketPrice;
    }
    public Double getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }
    public Double getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(Double totalCost) {
        this.totalCost = totalCost;
    }
    public Double getTotalPay() {
        return this.totalPay;
    }
    
    public void setTotalPay(Double totalPay) {
        this.totalPay = totalPay;
    }




}


