package com.entity;
// Generated Sep 7, 2019 8:57:10 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String FName;
     private String MName;
     private String address;
     private Integer mobile;
     private String email;
     private String gender;
     private Date dateOfBirth;
     private String nid;
     private String religion;
     private String occupation;
     private String city;
     private String country;
     private String typeOfUser;
     private String userName;
     private String password;

    public User() {
    }

    public User(String name, String FName, String MName, String address, Integer mobile, String email, String gender, Date dateOfBirth, String nid, String religion, String occupation, String city, String country, String typeOfUser, String userName, String password) {
       this.name = name;
       this.FName = FName;
       this.MName = MName;
       this.address = address;
       this.mobile = mobile;
       this.email = email;
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.nid = nid;
       this.religion = religion;
       this.occupation = occupation;
       this.city = city;
       this.country = country;
       this.typeOfUser = typeOfUser;
       this.userName = userName;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public String getMName() {
        return this.MName;
    }
    
    public void setMName(String MName) {
        this.MName = MName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Integer getMobile() {
        return this.mobile;
    }
    
    public void setMobile(Integer mobile) {
        this.mobile = mobile;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getNid() {
        return this.nid;
    }
    
    public void setNid(String nid) {
        this.nid = nid;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public String getOccupation() {
        return this.occupation;
    }
    
    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getTypeOfUser() {
        return this.typeOfUser;
    }
    
    public void setTypeOfUser(String typeOfUser) {
        this.typeOfUser = typeOfUser;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


